### PR TITLE
Button and Alert components are added

### PR DESCRIPTION
**Pull request by balaDharmaraj-81**

### CODE REVIEW

**Comment by Koushith** [comment]
LGTM. maybe you can create a components folder and move all the components inside. while opening a PR, you can add few sentences describing overall goals of the PR. 

ex- what was changed, feature or component description.

**Review by sakshi006 — COMMENTED** [review]
Looks good.

**Comment by balaDharmaraj-81** [comment]
> LGTM. maybe you can create a components folder and move all the components inside. while opening a PR, you can add few sentences describing overall goals of the PR.
> 
> ex- what was changed, feature or component description.

Sure will follow the same from next PRs. Thanks

**Comment by balaDharmaraj-81** [comment]
> Looks good.

Thank you so much

**Pull request merged**
